  [build]
    publish = "."

  [[headers]]
    for = "/pay.json"
    [headers.values]
      Link = '</pm-manifest.json>; rel="payment-method-manifest"'
      Content-Type = "application/json"
      Access-Control-Allow-Origin = "*"

  [[headers]]
    for = "/pm-manifest.json"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Content-Type = "application/json"
