[build]
    publish = "."

  [[headers]]
    for = "/pay.json"
    [headers.values]
      Link = '</pm-manifest.json>; rel="payment-method-manifest"'
      Content-Type = "application/json"
      Access-Control-Allow-Origin = "*"

  [[headers]]
    for = "/pm-manifest.json"
    [headers.values]
      Content-Type = "application/json"
      Access-Control-Allow-Origin = "*"

  [[headers]]
    for = "/app.json"
    [headers.values]
      Content-Type = "application/json"

  [[headers]]
    for = "/sw.js"
    [headers.values]
      Content-Type = "application/javascript"

  [[headers]]
    for = "/payload.js"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Cache-Control = "no-store, no-cache"

  [[headers]]
    for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, OPTIONS"
      Access-Control-Allow-Headers = "Content-Type"
      Cache-Control = "no-store, no-cache"
